### PR TITLE
fix(error): Fix error passthrough in queued tasks

### LINKED ISSUE #140: Errors from `chunkGetItem` are not handled
Errors from `chunkGetItem` seems to not be handled and instead I get the classic `Uncaught (in promise)` error
image

This is unfortunate because zarr.js happily returns an array full of zeroes and there is no error for me to catch or react on.

I think the issue might be that  `onIdle` from `p-queue` never throws?

The error I am seeing originates from [this line](https://github.com/gzuidhof/zarr.js/blob/a36a5e266aa434c7538edbcf34db8570295c9050/src/core/index.ts#L357) but I think similar issues could be present at more places in the codebase.

### PR DESCRIPTION
**Pull request by az0uz**
fixes #140

Errors being thrown by `chunkGetItem` (and underlying storage requests) are uncaught.

The use of the PQueue class will both emit an `error` event and throw if awaiting the Promise returned by the `queue.add` method.

To prevent this issue, I created an array of `queue.add` promises, and await for all those promises instead of using `queue.onIdle()`.

Using the error event will still be considered as uncaught errors since nothing is awaiting the queue.add promises.

### CODE REVIEW

**Comment by az0uz** [comment]
Right now, when there is a network issue in a chunk request, the get will still complete and return data, with that errored chunk data containing zeros, this change will fix that, and correctly throw on that method if any of the chunk requests errored. This will also throw the underlying AbortError when passing an AbortSignal to the Store through StoreOptions.

**Comment by toloudis** [comment]
I can confirm this is fixing a bug we have in our attempt to write a proxy Store to cache chunk requests.

File: src/core/index.ts [hunk 1]
```diff
@@ -339,28 +339,30 @@ export class ZarrArray<StoreGetOptions = any> {
...
       progressCallback({ progress: 0, queueSize: queueSize });
       for (const proj of indexer.iter()) {
-        (async () => {
+        allTasks.push((async () => {
           await queue.add(() => this.chunkGetItem(proj.chunkCoords, proj.chunkSelection, out, proj.outSelection, indexer.dropAxes, storeOptions));
           progress += 1;
           progressCallback({ progress: progress, queueSize: queueSize });
-        })();
+        })());
       }
```
Comment (manzt) [inline src/core/index.ts:356]: Hm, could we just use the queue but remove the async IIFE?

```js
queue.add(async () => {
  await this.chunkGetItem(proj.chunkCoords, proj.chunkSelection, out, proj.outSelection, indexer.dropAxes, storeOptions);
  progress += 1;
  progressCallback({ progress: progress, queueSize: queueSize });
});
```

Comment (manzt) [reply src/core/index.ts:356]: And then keep `queue.onIdle`?

Comment (toloudis) [reply src/core/index.ts:356]: I tried to do this and follow the pattern in the rest of the changes, but it brought back the same problem in my use case (trying to cancel chunk requests).  So maybe it's something about how PQueue.onIdle works...?

Comment (toloudis) [reply src/core/index.ts:356]: I wonder if the last part of this discussion https://github.com/sindresorhus/p-queue/issues/26 can inform the use of onIdle here.

Comment (az0uz) [reply src/core/index.ts:356]: I've looked into the implementation of p-queue while implementing this PR and it seems like the only way to correctly throw on the task error is to await the return of the `queue.add` method, [see here](https://github.com/sindresorhus/p-queue/blob/ce0c36440a28187ff3b3c0e0c91ab6d0d8093b05/source/index.ts#L281)
awaiting the `queue.onIdle` won't throw on error. So it seemed to me you have to create an Array of queue.add return promises and use await Promise.all on this Array.

Comment (manzt) [reply src/core/index.ts:356]: Ok! Thank you for looking into it and for your patience in my response. Would you mind still wrapping the full task in the `queue.add`:

```javascript
  const task = queue.add(async () => {
    await this.chunkGetItem(proj.chunkCoords, proj.chunkSelection, out, proj.outSelection, indexer.dropAxes, storeOptions);
    progress += 1;
    progressCallback({ progress: progress, queueSize: queueSize });
  });
  tasks.push(task);


// ... 

await promise.all(tasks);
```

Comment (az0uz) [reply src/core/index.ts]: Thanks for the suggestion, I've update the code to remove the iife and move the progress callback inside the queued task.

I didn't await for the progressCallback though since it is typed as returning void, I suggest this is done in a different PR?

Comment (manzt) [reply src/core/index.ts]: Great. Thank you!

**Review by manzt — APPROVED** [review]
LGTM
